### ISSUE TITLE
v8.0.0 Roadmap

### ISSUE THREAD

**Issue by ezimuel** [elastic/elastic-transport-php#3]
# Elastic-transport-php v8.0.0 Roadmap

- [x] Use [PHP-HTTP](https://docs.php-http.org/en/latest/) instead of Guzzle
- [x] Support async HTTP requests using [Promises/A+](https://promisesaplus.com/) open standard
- [x] Drop support for PHP 7.3

The work in progress of these tasks is available in [8.x branch](https://github.com/elastic/elastic-transport-php/tree/8.x)
